// Material Dashboard 3 PRO React components

import DefaultCell from "layouts/dashboards/sales/components/DefaultCell";

const dataTableData = {
  columns: [
    { Header: "ID", accessor: "id", width: "5%" },
    { Header: "Loại vi phạm", accessor: "violationType" },
    { Header: "Nhận diện", accessor: "detection" },
    { Header: "Cam ID", accessor: "camId" },
    { Header: "Bằng chứng", accessor: "evidence" },
    { Header: "Tình trạng", accessor: "status" },
    { Header: "Loại phương tiện", accessor: "vehicleType" },
    { Header: "Màu", accessor: "color" },
    { Header: "Biển số xe", accessor: "plateNumber" },
  ],

  rows: [
    {
      id: <DefaultCell>1</DefaultCell>,
      violationType: <DefaultCell>Vượt đèn đỏ</DefaultCell>,
      detection: <DefaultCell>CAM09786</DefaultCell>,
      camId: <DefaultCell>CAM09786</DefaultCell>,
      evidence: <DefaultCell>Hình ảnh/video</DefaultCell>,
      status: <DefaultCell>Đã xử lý</DefaultCell>,
      vehicleType: <DefaultCell>Ô tô</DefaultCell>,
      color: <DefaultCell>Trắng</DefaultCell>,
      plateNumber: <DefaultCell>37A-123.45</DefaultCell>,
    },
    {
      id: <DefaultCell>2</DefaultCell>,
      violationType: <DefaultCell>Lấn làn</DefaultCell>,
      detection: <DefaultCell>CAM09786</DefaultCell>,
      camId: <DefaultCell>CAM09786</DefaultCell>,
      evidence: <DefaultCell>Hình ảnh/video</DefaultCell>,
      status: <DefaultCell>Đã xử lý</DefaultCell>,
      vehicleType: <DefaultCell>Xe máy</DefaultCell>,
      color: <DefaultCell>Đen</DefaultCell>,
      plateNumber: <DefaultCell>29B1-678.90</DefaultCell>,
    },
    {
      id: <DefaultCell>3</DefaultCell>,
      violationType: <DefaultCell>Vượt tốc độ</DefaultCell>,
      detection: <DefaultCell>CAM09786</DefaultCell>,
      camId: <DefaultCell>CAM09786</DefaultCell>,
      evidence: <DefaultCell>Hình ảnh/video</DefaultCell>,
      status: <DefaultCell>Đã xử lý</DefaultCell>,
      vehicleType: <DefaultCell>Ô tô</DefaultCell>,
      color: <DefaultCell>Đỏ</DefaultCell>,
      plateNumber: <DefaultCell>51F-456.78</DefaultCell>,
    },
    {
      id: <DefaultCell>4</DefaultCell>,
      violationType: <DefaultCell>Lấn làn</DefaultCell>,
      detection: <DefaultCell>CAM09786</DefaultCell>,
      camId: <DefaultCell>CAM09786</DefaultCell>,
      evidence: <DefaultCell>Hình ảnh/video</DefaultCell>,
      status: <DefaultCell>Đã xử lý</DefaultCell>,
      vehicleType: <DefaultCell>Xe máy</DefaultCell>,
      color: <DefaultCell>Đen</DefaultCell>,
      plateNumber: <DefaultCell>29B1-678.91</DefaultCell>,
    },
    {
      id: <DefaultCell>5</DefaultCell>,
      violationType: <DefaultCell>Vượt tốc độ</DefaultCell>,
      detection: <DefaultCell>CAM09786</DefaultCell>,
      camId: <DefaultCell>CAM09786</DefaultCell>,
      evidence: <DefaultCell>Hình ảnh/video</DefaultCell>,
      status: <DefaultCell>Đã xử lý</DefaultCell>,
      vehicleType: <DefaultCell>Ô tô</DefaultCell>,
      color: <DefaultCell>Đỏ</DefaultCell>,
      plateNumber: <DefaultCell>51F-456.79</DefaultCell>,
    },
    {
      id: <DefaultCell>6</DefaultCell>,
      violationType: <DefaultCell>Lấn làn</DefaultCell>,
      detection: <DefaultCell>CAM09786</DefaultCell>,
      camId: <DefaultCell>CAM09786</DefaultCell>,
      evidence: <DefaultCell>Hình ảnh/video</DefaultCell>,
      status: <DefaultCell>Đã xử lý</DefaultCell>,
      vehicleType: <DefaultCell>Xe máy</DefaultCell>,
      color: <DefaultCell>Đen</DefaultCell>,
      plateNumber: <DefaultCell>29B1-678.92</DefaultCell>,
    },
    {
      id: <DefaultCell>7</DefaultCell>,
      violationType: <DefaultCell>Vượt tốc độ</DefaultCell>,
      detection: <DefaultCell>CAM09786</DefaultCell>,
      camId: <DefaultCell>CAM09786</DefaultCell>,
      evidence: <DefaultCell>Hình ảnh/video</DefaultCell>,
      status: <DefaultCell>Đã xử lý</DefaultCell>,
      vehicleType: <DefaultCell>Ô tô</DefaultCell>,
      color: <DefaultCell>Đỏ</DefaultCell>,
      plateNumber: <DefaultCell>51F-456.80</DefaultCell>,
    },
    {
      id: <DefaultCell>8</DefaultCell>,
      violationType: <DefaultCell>Lấn làn</DefaultCell>,
      detection: <DefaultCell>CAM09786</DefaultCell>,
      camId: <DefaultCell>CAM09786</DefaultCell>,
      evidence: <DefaultCell>Hình ảnh/video</DefaultCell>,
      status: <DefaultCell>Đã xử lý</DefaultCell>,
      vehicleType: <DefaultCell>Xe máy</DefaultCell>,
      color: <DefaultCell>Đen</DefaultCell>,
      plateNumber: <DefaultCell>29B1-678.93</DefaultCell>,
    },
    {
      id: <DefaultCell>9</DefaultCell>,
      violationType: <DefaultCell>Vượt tốc độ</DefaultCell>,
      detection: <DefaultCell>CAM09786</DefaultCell>,
      camId: <DefaultCell>CAM09786</DefaultCell>,
      evidence: <DefaultCell>Hình ảnh/video</DefaultCell>,
      status: <DefaultCell>Đã xử lý</DefaultCell>,
      vehicleType: <DefaultCell>Ô tô</DefaultCell>,
      color: <DefaultCell>Đỏ</DefaultCell>,
      plateNumber: <DefaultCell>51F-456.81</DefaultCell>,
    },
  ],
};

export default dataTableData;
